apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    envFrom:
    - configMapRef:
        name: app-cm1
