apiVersion: v1
kind: Pod
metadata:
  name: redis-nginx-pod
  labels:
    app: redis-nginx-demo
spec:
  containers:
    - name: redis-container
      image: redis:latest
      ports:
        - containerPort: 6379 # Default Redis port
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80 # Default Nginx port

