apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: adam
spec:
  signerName: kubernetes.io/kube-apiserver-client
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VZV1JoYlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU5BRHgyc2M5RWtBSk9lK2VSYUs0enZDb0gvdXpqdUNBUTZ0V0dVZ0pVcEV4aUI5CjB3cWc4aExLQ2FlVWJTRlZZSm5uWVRXSTdsdjkrNERBZHIxMnVUZTV0UHJPdkJRT3RQSzRFRFJ1NU5QNkNJVmIKcnhSRXZhaTg2OE5xQ0VNQnpXKy92QXc3enEyQ1hqT21jVzVhdVVhYmxwa2c0b0k1VkV2R3pER1hMN0VOaU54NQpLTE9XSEZ5SDB2ZzdMV2dodTVCSVJIRmtJSEZ3WDJ0MHduZmttbGhBbjJrUmJGMXJEUmhwM0ZMYXRycHlRcWI3Cm1TSDl4Wi8xeURwWW1zNHc3UjRLVVlLUE1GQ2cvMnRmbW9MRDNxcnQrRGlhbWUwcHJCaHBFQlUrYjE2ZEtISzEKRm5lVnVXMVFpUnlxbXVnK2FqbmZRSGtNVXpOVWswVGxWMnJzNVdzQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQVozOElVMG9kei9DTUtKUHRDSjNpV2VIYXFONnpMejlrYlhSbHZpbVA0eWwyRVZKc2U1QlE2ClVEcS9HeHlLWGFyYjN3eHE2ZkFMQ3NQSW1XbHNNU29hYTFVSUhkMldNREhRaS9oZ1AzTXdBSVZPT09tWU9iREUKbFZSaFoyZFNQcWxUeThRZ2NkM0p4bnBsU2oyVE13V1hMUGhvNHpCTm8wbWM0dEFQQUhLK25VcXF3ZTVQdmllOQpiOTZpVGRPanIrTDEvamR3YjJRNkg1aDJSWjdGMlZ1UjV2bDExNFYvRVVHZ0hIN25IQ3NwRkRrMUd4YVZmQkFNCjZWN3F3UmFnVXMvR1JaTG13dXZTQzNZb2hWbzhDUEd1cSs0TW10MXV0UFBLZ0JrKy9ZVVpDeGlGQWV0NWNabXUKNm1vMlUyRFR6WnpkV1NJcy9TMGdaOHBuWUxma1hVb2wKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  expirationSeconds: 86400
  usages:
    - client auth

