apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc  # Added name for the replication controller
  labels:
    app: nginx-rc
    env: Demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        env: demo
        name: nginx
    spec:
      containers:
        - image: nginx
          name: nginx

