apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000  # Exposing the registry on port 30000
  type: NodePort  # Change this to NodePort

